version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA21novTestProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
services:
- serviceName: project.siqa21novtest.integrations:ValidateSchemaTPPinDAF
  packages:
  - name: SIQA21novTestProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.schema:validate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
